<?php

namespace BMurphy\Proxies\__CG__\BMurphy\Models;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \BMurphy\Models\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setId($value)
    {
        $this->__load();
        return parent::setId($value);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setUsername($value)
    {
        $this->__load();
        return parent::setUsername($value);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setEmail($value)
    {
        $this->__load();
        return parent::setEmail($value);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setSalt($value)
    {
        $this->__load();
        return parent::setSalt($value);
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function setPassword($value)
    {
        $this->__load();
        return parent::setPassword($value);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setCreated($value)
    {
        $this->__load();
        return parent::setCreated($value);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setUpdated($value)
    {
        $this->__load();
        return parent::setUpdated($value);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setClients($value)
    {
        $this->__load();
        return parent::setClients($value);
    }

    public function getClients()
    {
        $this->__load();
        return parent::getClients();
    }

    public function setCodes($value)
    {
        $this->__load();
        return parent::setCodes($value);
    }

    public function getCodes()
    {
        $this->__load();
        return parent::getCodes();
    }

    public function setTokens($value)
    {
        $this->__load();
        return parent::setTokens($value);
    }

    public function getTokens()
    {
        $this->__load();
        return parent::getTokens();
    }

    public function set($name, $value)
    {
        $this->__load();
        return parent::set($name, $value);
    }

    public function get($name)
    {
        $this->__load();
        return parent::get($name);
    }

    public function fromArray($array)
    {
        $this->__load();
        return parent::fromArray($array);
    }

    public function toArray($withAssociations = true)
    {
        $this->__load();
        return parent::toArray($withAssociations);
    }

    public function offsetExists($name)
    {
        $this->__load();
        return parent::offsetExists($name);
    }

    public function offsetSet($name, $value)
    {
        $this->__load();
        return parent::offsetSet($name, $value);
    }

    public function offsetGet($name)
    {
        $this->__load();
        return parent::offsetGet($name);
    }

    public function offsetUnset($name)
    {
        $this->__load();
        return parent::offsetUnset($name);
    }

    public function checkEntityManagerIsClear()
    {
        $this->__load();
        return parent::checkEntityManagerIsClear();
    }

    public function isNew()
    {
        $this->__load();
        return parent::isNew();
    }

    public function checkIsNew()
    {
        $this->__load();
        return parent::checkIsNew();
    }

    public function checkIsNotNew()
    {
        $this->__load();
        return parent::checkIsNotNew();
    }

    public function isModified()
    {
        $this->__load();
        return parent::isModified();
    }

    public function checkIsModified()
    {
        $this->__load();
        return parent::checkIsModified();
    }

    public function checkIsNotModified()
    {
        $this->__load();
        return parent::checkIsNotModified();
    }

    public function getModified()
    {
        $this->__load();
        return parent::getModified();
    }

    public function refresh()
    {
        $this->__load();
        return parent::refresh();
    }

    public function changeSet()
    {
        $this->__load();
        return parent::changeSet();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }

    public function updateTimestampableCreated()
    {
        $this->__load();
        return parent::updateTimestampableCreated();
    }

    public function updateTimestampableUpdated()
    {
        $this->__load();
        return parent::updateTimestampableUpdated();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'email', 'salt', 'password', 'created', 'updated', 'clients', 'codes', 'tokens');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}